title: android stuff & co.
description: Gautier's personal development blog
author: Gautier Mechling
baseurl: ""
url: "http://nilhcem.com"
twitter_username: Nilhcem
github_username: Nilhcem

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
