title: Gautier Mechling
description: Android stuff & co
baseurl: ""
url: "http://nilhcem.com"
twitter_username: Nilhcem
github_username: Nilhcem
avatar: https://avatars3.githubusercontent.com/u/1016119

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
