title: Gautier Mechling
description: Android stuff & co
baseurl: ""
url: "http://nilhcem.com"
twitter_username: Nilhcem
github_username: Nilhcem

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
